ReaderProcessor
indica-mcf/Indica pull request #364
Opened 2024-12-10 13:39 UTC by michael-gemmell

ReadST40 renamed to ReaderProcessor and unnecessary methods removed

ST40Reader now does the reading!

2024-12-12 08:55 UTC, marcosertoli requested changes
Looks good! Just a few minor comments/mods.

2024-12-12 09:13 UTC, michael-gemmell commented on indica/workflows/_load_modelling_plasma.py
Absolutely not!

2024-12-12 16:00 UTC, michael-gemmell commented
Done!

2024-12-14 09:32 UTC, marcosertoli approved these changes

2024-12-14 09:32 UTC, merged